version: "3.8"

services:
  php:
    build:
      dockerfile_inline: |
        FROM php:8.3-apache
        RUN docker-php-ext-install pdo pdo_mysql
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: projeto3
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
